### ISSUE TITLE
not compatible with projects that use pyproject.toml

### ISSUE THREAD

**Issue by antonag32** [Vauxoo/pre-commit-vauxoo#118]
As of now pre-commit-vauxoo is not compatible with projects that use `pyproject.toml` for other things like declaring build systems, project information, or other tooling, as it completely overwrites it.

Instead of completely overwriting the whole file, I think there are two options:

1. Merge the config sources
2. Rename black's config file to something else so it does not conflicts with the project's main pyproject.toml

I like number two because it is easier and means the file can still be ignored without ignoring the project's original pyproject.toml

**Comment by moylop260** [comment]
For now, we can revert the local change for this file before to commit it

Or even using an .gitignore in order to ignore these changes

Even the most of the project used this package is for odoo modules and they don't have `pyproject.toml` file

So, IMHO we should not dedicate too much to fix this

Instead of we could make a workaround about
