### ISSUE TITLE
[BUG] xml-duplicate-fields must ignore when the field has attr invisible

### ISSUE THREAD

**Issue by fernandahf** [Vauxoo/pre-commit-vauxoo#85]
Usually, we hide/show the same field in the same view with different contexts in order to show them with different strings, this is a valid case, but right now the lint `xml-duplicate-fields` is detected for these kinds of cases even if the field has the attribute invisible.

**Comment by fernandahf** [comment]
FYI @antonag32  @moylop260

**Comment by moylop260** [comment]
Summary ignore if `invisible=*`

**Comment by luisg123v** [comment]
IMHO this shouldn't consider fields inside arch, because there are tons of valid cases using duplicated fields:
- one field in edit mode and another on readonly mode
- One invisible and another visible
- Same field with different attrs, e.g. in invoices
- Same field and same attrs (because attrs are set in the contained group), e.g. leads and opportunities. Here fields are "duplicated"
- Same field on different context, e.g. field "name" in partner is present also in child partners

AFAIK this lint was meant to detect duplicated fields inside a record, which would be the equivalent of detecting the same key on a create/write method.

**Comment by moylop260** [comment]
@luisg123v 

You are the second person saying something similar...

Should we delete this check?

**Comment by antonag32** [comment]
For the record. We have decided not to look into any children as stated previously.
So this will be valid:

```
<record id="magicalid" model"magic.magic">
  <field name="with_children">
    <field name="same">
    <field name="same">
  </fied>
</record>
```

But this will be invalid:
```
<record id="magicalid" model"magic.magic">
  <field name="with_children">...</field>
  <field name="with_children">...</field>
</record>
```

On realistic/practical terms this means the lint will only make sure you don't create/write an xml record that has duplicate fields, and views (since they are a children of `field name="arch"`) wont be checked, at least for duplicate fields.

**Comment by moylop260** [comment]
@antonag32 

Could you migrate the summary of this issue to [odoo-pre-commit-hooks](https://github.com/OCA/odoo-pre-commit-hooks/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=), please

**Comment by moylop260** [comment]
Superseded by https://github.com/OCA/odoo-pre-commit-hooks/issues/56
